# Generated by Django 5.2.7 on 2025-11-01 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NT8Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firm_name",
                    models.CharField(
                        choices=[
                            ("apex", "Apex Trader Funding"),
                            ("takeprofit", "Take Profit Trader"),
                            ("onestep", "OneStep Funding"),
                            ("topstep", "TopStep Trader"),
                            ("hyrotrader", "HyroTrader (Crypto)"),
                            ("other", "Other"),
                        ],
                        help_text="Prop firm or broker name",
                        max_length=50,
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        help_text="Account number or identifier", max_length=100
                    ),
                ),
                (
                    "socket_port",
                    models.IntegerField(
                        help_text="Unique TCP port for this account (e.g., 8080, 8081)",
                        unique=True,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this account should receive signals",
                    ),
                ),
                (
                    "last_signal_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last signal sent to this account",
                        null=True,
                    ),
                ),
                (
                    "open_positions_count",
                    models.IntegerField(
                        default=0, help_text="Current number of open positions"
                    ),
                ),
                (
                    "daily_pnl",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Today's profit/loss in USD",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Owner of this NT8 account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nt8_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "NT8 Account",
                "verbose_name_plural": "NT8 Accounts",
                "ordering": ["-active", "firm_name", "account_number"],
                "unique_together": {("user", "firm_name", "account_number")},
            },
        ),
        migrations.CreateModel(
            name="SignalLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signal_data",
                    models.JSONField(
                        help_text="Complete signal payload (action, instrument, price, TP, SL)"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When signal was sent"
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=False,
                        help_text="Whether signal was successfully delivered",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error details if delivery failed",
                        null=True,
                    ),
                ),
                (
                    "latency_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Signal delivery latency in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="NT8 account that received this signal",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="ninja.nt8account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Signal Log",
                "verbose_name_plural": "Signal Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="ninja_signa_timesta_4e34ba_idx"
                    ),
                    models.Index(
                        fields=["account", "-timestamp"],
                        name="ninja_signa_account_743dc4_idx",
                    ),
                    models.Index(
                        fields=["success", "-timestamp"],
                        name="ninja_signa_success_4f9e81_idx",
                    ),
                ],
            },
        ),
    ]
